spring:
  jpa:
    database: postgresql
#    hibernate.ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-34-236-56-112.compute-1.amazonaws.com/ddehhj8lhcloin
    username: fyvamghtfnvtuv
    password: ef9cda0c03867c33907bd7b97d8af41480b064464f1ff920248a7ee697c0121e
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  redis:
    url: redis://:pc027b408df224efd230a37c09a8835d51f060d6385b1387c8591922171266cac@ec2-23-22-33-14.compute-1.amazonaws.com:23059

jwt:
  secret-key: yeongjun.sns-application-2023.secret_key
  token:
    expired-time-ms: 3600000

